In [1]:
import numpy as np
from neuron import Neuron

## Test on AND 

In [2]:
# AND table
data = np.array([
    # A  B  O
    [0, 0, 0],
    [0, 1, 0],
    [1, 0, 0],
    [1, 1, 1],
])
data

array([[0, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 1, 1]])

In [3]:
x = data[:, :-1]
y = data[:, -1:]

print(x)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [0]
 [0]
 [1]]


## Add bias to input

In [4]:
x_bias = np.ones((x.shape[0], 1))
x_train = np.c_[x, x_bias]
x_train

array([[0., 0., 1.],
       [0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

## Create neuron and train
* we train by looping over all examples untill the neuron do not fails or we run more then 100 times.

In [5]:
n = Neuron(x_train, y)
n.weights

array([[0.],
       [0.],
       [0.]])

In [8]:
n = Neuron(x_train, y)

end_run = -1

for i in range(100):
    print("\n-------- run", i, "--------")
    err = 0
    done = True
    for j in range(x_train.shape[0]):
        pred = n.predict(x_train[j])
        actual = y[j]
        print("prediction :", pred, ", actual :", actual[0])
        change = n.train_one(x_train[j], actual)
        if change:
            err += 1
            done = False
    if done:
        end_run = i
        break
    else:
        print("End of run Num of Errors :", err)
        print("weights : ")
        print(n.weights)


-------- run 0 --------
prediction : 0 , actual : 0
prediction : 0 , actual : 0
prediction : 0 , actual : 0
prediction : 0 , actual : 1
End of run Num of Errors : 1
weights : 
[[0.33333333]
 [0.33333333]
 [0.33333333]]

-------- run 1 --------
prediction : 1 , actual : 0
prediction : 0 , actual : 0
prediction : 0 , actual : 0
prediction : 0 , actual : 1
End of run Num of Errors : 2
weights : 
[[ 0.66666667]
 [ 0.66666667]
 [-0.33333333]]

-------- run 2 --------
prediction : 0 , actual : 0
prediction : 1 , actual : 0
prediction : 0 , actual : 0
prediction : 0 , actual : 1
End of run Num of Errors : 2
weights : 
[[ 1. ]
 [ 0.5]
 [-0.5]]

-------- run 3 --------
prediction : 0 , actual : 0
prediction : 0 , actual : 0
prediction : 1 , actual : 0
prediction : 0 , actual : 1
End of run Num of Errors : 2
weights : 
[[ 0.83333333]
 [ 0.83333333]
 [-0.66666667]]

-------- run 4 --------
prediction : 0 , actual : 0
prediction : 1 , actual : 0
prediction : 0 , actual : 0
prediction : 0 , actual

In [7]:
print("\n------ training done ------")
print("training done on run :", end_run)
print("final weights :")
print(n.weights)


------ training done ------
training done on run : 6
final weights :
[[ 1.]
 [ 1.]
 [-1.]]
